name: Test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "GITHUB_TOKEN scope test"
          curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/$GITHUB_REPOSITORY | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get(\"permissions\",{}))"
